### ISSUE TITLE
EXIF rotation is ignored

### ISSUE THREAD

**Issue by gregorni** [FineFindus/artem#16] opened 2023-06-24 14:56 UTC
When converting images shot on a smartphone in portrait mode, the output is rotated anti-clockwise by 90°. This might have to do with the image metadata not being read properly, or at least not the part that tells that the image is rotated 90°.

jp2a and ascii-image-converter have the same issue

**Comment by gregorni** [comment] 2023-06-24 14:58
<details><summary>Example photo:</summary>

![2023-02-05-15-59-45-806](https://github.com/FineFindus/artem/assets/119804311/bdc62d04-08d9-48b2-a43e-37240133905e)

</details>

**Comment by FineFindus** [comment] 2023-06-24 18:55
The problem is that this isn't actually a rotated image, it's a horizontal image with EXIF data that rotates it. The image library used by artem [does not support reading EXIF data](https://github.com/image-rs/image/issues/1045), so this is not an easy problem to solve. While it is possible to implement code to read the EXIF, this would only partially solve the problem, as most EXIF readers do not support all available formats.

Perhaps support for rotating the image with a new argument would solve the problem?

**Comment by gregorni** [comment] 2023-06-24 20:06
This does seem like an issue the library should fix, to be honest. I find it weird that nearly all ASCII converters have this issue, regardless of their programming language.

**Comment by FineFindus** [comment] 2023-06-25 10:47
I'm closing this for now, as this is not the right place to track the upstream issue (which seems unlikely to be resolved soon). Feel free to reopen it if you disagree.

**Closed by FineFindus** 2023-06-25 10:47 UTC
Labels: bug, upstream
